INSERT INTO Verb (verb, auxverb, partizip, translation) VALUES
('gehen', 'ist', 'gegangen', 'ходить'),
('kochen', 'hat', 'gekocht', 'готовить (пищу)'),
('vergessen', 'hat', 'vergessen', 'забывать'),
('reden', 'hat', 'geredet', 'разговаривать, беседовать'),
('lachen', 'hat', 'gelacht', 'смеяться'),
('kaufen', 'hat', 'gekauft', 'покупать'),
('singen', 'hat', 'gesungen', 'петь'),
('bezahlen', 'hat', 'bezahlt', 'платить'),
('steigen', 'ist', 'gestiegen', 'подниматься'),
('klettern', 'ist', 'geklettert', 'карабкаться'),
('schreiben', 'hat', 'geschrieben', 'писать'),
('sehen', 'hat', 'gesehen', 'смотреть'),
('springen', 'ist', 'gesprungen', 'прыгать'),
('backen', 'ist', 'gebacken', 'печь'),
('schwimmen', 'ist', 'geschwommen', 'плавать'),
('besuchen', 'hat', 'besucht', 'навещать'),
('reparieren', 'hat', 'repariert', 'чинить'),
('weinen', 'hat', 'geweint', 'плакать'),
('anrufen', 'hat', 'angerufen', 'звонить'),
('ausdenken', 'hat', 'ausgedacht', 'выдумывать'),
('essen', 'hat', 'gegessen', 'кушать'),
('schauen', 'hat', 'geschaut', 'смотреть'),
('bleiben', 'ist', 'geblieben', 'оставаться'),
('fotografieren', 'hat', 'fotografiert', 'фотографировать'),
('probieren', 'hat', 'probiert', 'пытаться'),
('suchen', 'hat', 'gesucht', 'искать'),
('schmücken', 'hat', 'geschmückt', 'украшать'),
('tragen', 'hat', 'getragen', 'носить'),
('gefallen', 'hat', 'gefallen', 'нравиться'),
('malen', 'hat', 'gemalt', 'рисовать'),
('kreuzen', 'hat', 'gekreuzt', 'перекрещивать'),
('bieten', 'hat', 'geboten', 'предлагать'),
('rauchen', 'hat', 'geraucht', 'курить');