INSERT INTO Verb (verb, auxverb, partizip, translation) VALUES
('unterrichten', 'hat', 'unterrichtet', 'pouczać'),
('sagen', 'hat', 'gesagt', 'powiedzieć'),
('sorgen', 'hat', 'gesorgt', 'troszczyć się'),
('nehmen', 'hat', 'genommen', 'brać'),
('akzeptieren', 'hat', 'akzeptiert', 'akceptować'),
('verweigern', 'hat', 'verweigert', 'odmawiać'),
('dienen', 'hat', 'gedient', 'służyć'),
('schaden', 'hat', 'geschadet', 'szkodzić'),
('basteln', 'hat', 'gebastelt', 'majsterkować'),
('biegen', 'hat', 'gebogen', 'giąć'),
('fragen', 'hat', 'gefragt', 'pytać'),
('hindern', 'hat', 'gehindert', 'przeszkadzać'),
('bieten', 'hat', 'geboten', 'oferować'),
('antworten', 'hat', 'geantwortet', 'odpowiadać'),
('erstellen', 'hat', 'erstellt', 'sporządzać'),
('verfassen', 'hat', 'verfasst', 'układać'),
('helfen', 'hat', 'geholfen', 'pomagać'),
('arbeiten', 'hat', 'gearbeitet', 'pracować '),
('nähen', 'hat', 'genäht', 'szyć'),
('säubern', 'hat', 'gesäubert', 'czyścić'),
('abbrechen', 'hat', 'abgebrochen', 'przestawać '),
('greifen', 'hat', 'gegriffen', 'chwytać'),
('benützen', 'hat', 'benützt', 'używać'),
('brauchen', 'hat', 'gebraucht', 'potrzebować'),
('waschen', 'hat', 'gewaschen', 'myć'),
('verbessern', 'hat', 'verbessert', 'ulepszać'),
('entwickeln', 'hat', 'entwickelt', 'rozwijać'),
('zeigen', 'hat', 'gezeigt', 'pokazywać ');