INSERT INTO Verb (verb, auxverb, partizip, translation) VALUES
('gehen', 'ist', 'gegangen', 'chodzić'),
('kochen', 'hat', 'gekocht', 'gotować'),
('vergessen', 'hat', 'vergessen', 'zapominać'),
('reden', 'hat', 'geredet', 'rozmawiać, gadać'),
('lachen', 'hat', 'gelacht', 'śmiać się'),
('kaufen', 'hat', 'gekauft', 'kupować'),
('singen', 'hat', 'gesungen', 'spiewać'),
('bezahlen', 'hat', 'bezahlt', 'płacić '),
('steigen', 'ist', 'gestiegen', 'iść w górę'),
('klettern', 'ist', 'geklettert', 'wspinać się'),
('schreiben', 'hat', 'geschrieben', 'pisać'),
('sehen', 'hat', 'gesehen', 'patrzeć'),
('springen', 'ist', 'gesprungen', 'skakać'),
('backen', 'ist', 'gebacken', 'piec'),
('schwimmen', 'ist', 'geschwommen', 'pływać'),
('besuchen', 'hat', 'besucht', 'odwiedzać'),
('reparieren', 'hat', 'repariert', 'naprawiać'),
('weinen', 'hat', 'geweint', 'płakać'),
('anrufen', 'hat', 'angerufen', 'telefonować'),
('ausdenken', 'hat', 'ausgedacht', 'wymyślać'),
('essen', 'hat', 'gegessen', 'jeść'),
('schauen', 'hat', 'geschaut', 'spoglądać'),
('bleiben', 'ist', 'geblieben', 'zostawać'),
('fotografieren', 'hat', 'fotografiert', 'fotografować'),
('probieren', 'hat', 'probiert', 'próbować '),
('suchen', 'hat', 'gesucht', 'szukać'),
('schmücken', 'hat', 'geschmückt', 'ozdabiać'),
('tragen', 'hat', 'getragen', 'nosić'),
('gefallen', 'hat', 'gefallen', 'podobać się'),
('malen', 'hat', 'gemalt', 'malować'),
('kreuzen', 'hat', 'gekreuzt', 'krzyżować'),
('bieten', 'hat', 'geboten', 'oferować'),
('rauchen', 'hat', 'geraucht', 'palić');